public virtual class Smartv {
 Private String resolocao;
 Private String tamanhoTela;
 Private String frequencia;      
 Private Boolean conexaoWifi;
    
     public String getResolocao(){
        return resolocao;
    }
    public void setResolocao(String resolocao){
        this.resolocao = resolocao;
        }
        
        public String getTamanhoTelar(){
        return tamanhoTela;
    }
    public void setTamanhoTela(String tamanhoTela){
        this.tamanhoTela = tamanhoTela;
        }
        
        public String getFrequencia(){
        return frequencia;
    }
    public void setFrequencia(String frequencia){
        this.frequencia = frequencia;
        }
        
        public Boolean getConexaoWifi(){
        return conexaoWifi;
    }
    public void setConexaoWifi(Boolean conexaoWifi){
        this.conexaoWifi = conexaoWifi;
     }
    
    }